# Copyright (C) 2025 Frachtwerk GmbH, Leopoldstra√üe 7C, 76133 Karlsruhe.
#
# This file is part of essencium-backend.
#
# essencium-backend is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# essencium-backend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with essencium-backend. If not, see <http://www.gnu.org/licenses/>.

debug: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    de.frachtwerk: DEBUG

server:
  port: 8098
  error:
    include-stacktrace: always

spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false

mail:
  # See https://ethereal.email
  host: localhost
  port: 1025
  username: noreply@essencium.dev
  password: secret

  branding:
    url: http://localhost:8098/

  default-sender:
    address: noreply@essencium.dev
  # debug-receiver: #possible debug-receiver
  #   active: true
  contact-mail:
    subject-prefix-key: mail.contact.subject.prefix
    recipients:
      - noreply@essencium.dev
    template: ContactMessage.ftl
    locale: de

sentry:
  # Need to set Environment in Container-Stack
  environment:

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
